// Map of country/nationality/language names to emoji flags
const flagMap: Record<string, string> = {
  // Countries
  spain: "🇪🇸",
  france: "🇫🇷",
  germany: "🇩🇪",
  sweden: "🇸🇪",
  denmark: "🇩🇰",
  portugal: "🇵🇹",
  norway: "🇳🇴",
  croatia: "🇭🇷",
  serbia: "🇷🇸",
  hungary: "🇭🇺",
  poland: "🇵🇱",
  romania: "🇷🇴",
  iceland: "🇮🇸",
  egypt: "🇪🇬",
  tunisia: "🇹🇳",
  qatar: "🇶🇦",
  japan: "🇯🇵",
  "south korea": "🇰🇷",
  brazil: "🇧🇷",
  argentina: "🇦🇷",
  usa: "🇺🇸",
  "united states": "🇺🇸",
  canada: "🇨🇦",
  uk: "🇬🇧",
  "united kingdom": "🇬🇧",
  england: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  netherlands: "🇳🇱",
  belgium: "🇧🇪",
  switzerland: "🇨🇭",
  austria: "🇦🇹",
  italy: "🇮🇹",
  greece: "🇬🇷",
  turkey: "🇹🇷",
  russia: "🇷🇺",
  slovenia: "🇸🇮",
  "czech republic": "🇨🇿",
  slovakia: "🇸🇰",
  finland: "🇫🇮",
  israel: "🇮🇱",
  morocco: "🇲🇦",
  algeria: "🇩🇿",
  
  // Nationalities
  spanish: "🇪🇸",
  french: "🇫🇷",
  german: "🇩🇪",
  swedish: "🇸🇪",
  danish: "🇩🇰",
  portuguese: "🇵🇹",
  norwegian: "🇳🇴",
  croatian: "🇭🇷",
  serbian: "🇷🇸",
  hungarian: "🇭🇺",
  polish: "🇵🇱",
  romanian: "🇷🇴",
  icelandic: "🇮🇸",
  egyptian: "🇪🇬",
  tunisian: "🇹🇳",
  brazilian: "🇧🇷",
  dutch: "🇳🇱",
  belgian: "🇧🇪",
  swiss: "🇨🇭",
  austrian: "🇦🇹",
  italian: "🇮🇹",
  british: "🇬🇧",
  american: "🇺🇸",
  canadian: "🇨🇦",
  greek: "🇬🇷",
  turkish: "🇹🇷",
  russian: "🇷🇺",
  slovenian: "🇸🇮",
  czech: "🇨🇿",
  slovak: "🇸🇰",
  finnish: "🇫🇮",

  // Languages
  english: "🇬🇧",
  arabic: "🇸🇦",
};

export function getFlag(name: string): string {
  return flagMap[name.toLowerCase()] || "🏳️";
}
